apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-service.fullname" . }}
  labels:
    app: {{ include "backend-service.name" . }}
annotations:
  service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  selector:
    app: {{ include "backend-service.name" . }}
  ports:
    - port: 80 #yeah this should be 443 or other https->ssl matcher
      targetPort: 80 #yeah this should be more secure
  type: LoadBalancer
