apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "frontend-service.fullname" . }}
  labels:
    app: {{ include "frontend-service.name" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: customer.sandbox.curve.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "frontend-service.fullname" . }}
                port:
                  number: 80 #could be 443 or 8443
                
