apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend-service.fullname" . }}
  labels:
    app: {{ include "frontend-service.name" . }}
annotations:
  service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  selector:
    app: {{ include "frontend-service.name" . }}
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
